# Generated by Django 4.1.3 on 2023-01-08 05:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author",
            new_name="author_name",
        ),
        migrations.AddField(
            model_name="book",
            name="publisher_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publisher_email", models.CharField(max_length=200)),
                (
                    "publisher_name",
                    models.ForeignKey(
                        blank=True,
                        max_length=200,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=1)),
                ("email", models.CharField(max_length=100)),
                (
                    "author_name",
                    models.ForeignKey(
                        blank=True,
                        max_length=200,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.book",
                    ),
                ),
            ],
        ),
    ]
